In [2]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('01-tensor-operations')
jovian.set_colab_id('1TS5fmJ2CJG6whuONWLTREnJb52_PYAZ3')

     |████████████████████████████████| 68 kB 4.0 MB/s 


# Pytorch Tensor basic function

An short introduction about PyTorch and about the chosen functions. 

- Create tensor
- convert numpy to tensor
- calculate gradient
- make all element of matrix to zeros and ones
- Repeats tensor along the specified dimensions.

Before we begin, let's install and import PyTorch

In [4]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor (change this)

Add some explanations

In [5]:
# Example 1 - working (change this)
torch.tensor([[1, 2], [3, 4.]])

tensor([[1., 2.],
        [3., 4.]])

this function make 2x2 matrix of tensor.

In [6]:
# Example 2 - working
torch.tensor([[3,5,9],
              [3,9,1],
              [45,8,2]])

tensor([[ 3,  5,  9],
        [ 3,  9,  1],
        [45,  8,  2]])

created 3x3 matrix of tensor

In [7]:
# Example 3 - breaking (to illustrate when it breaks)
torch.tensor([[1, 2], [3, 4, 5]])

ValueError: ignored

## Function 2. convert numpy to tensor

Add some explanations

In [13]:
import numpy as np
import torch


x = np.array([[3,5],
              [3,7]], dtype = 'float32')
x = torch.from_numpy(x)
print(x)

tensor([[3., 5.],
        [3., 7.]])


in above example i have import numpy and torch then converted 2d numpy array into tensor

In [14]:
x = np.array([[4,6,2],
              [6,1,8],
              [3,56,2]], dtype = 'float64')
y = torch.from_numpy(x)
print(y)


tensor([[ 4.,  6.,  2.],
        [ 6.,  1.,  8.],
        [ 3., 56.,  2.]], dtype=torch.float64)


in above example i have converted 3d numpy array into tensors

In [15]:
# Example 3 - breaking (to illustrate when it breaks)
for i in range(10):
  if i == 7:
    break
  print(i)

0
1
2
3
4
5
6


## Function 3. calculate gradient

Add some explanations

in this example i have initialize 3x3 randomly weights

In [17]:
# Example 1 
w = torch.randn(3,3)
print(w)

tensor([[-1.9237, -1.1792, -1.6047],
        [ 0.9605,  0.9766, -2.7487],
        [ 0.6484, -1.0210, -0.4987]])


In [18]:
# Example 2
w = torch.randn(2, 3, requires_grad= True)
print(w)

tensor([[1.2248, 0.2497, 1.2214],
        [1.3072, 0.7260, 0.1455]], requires_grad=True)


if we set requires_grad = True then it can compute gradient otherwise we can compute

In [19]:
# Example 3 
print(w.grad)

None
